CREATE DATABASE OFFICE;
SHOW DATABASES;
USE OFFICE;
CREATE TABLE OFFICE (
    ID INT NOT NULL,
    NAME VARCHAR(20) UNIQUE NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(25) NOT NULL,
    SALARY DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (ID)
);
INSERT INTO OFFICE (ID, NAME, AGE, ADDRESS, SALARY) VALUES
(1, 'John', 30, 'New York', 55000.00),
(2, 'Jane', 25, 'Los Angeles', 48000.00),
(3, 'Peter', 45, 'Chicago', 75000.00),
(4, 'Mary', 28, 'Houston', 62000.00);
SELECT * FROM OFFICE;
ALTER TABLE OFFICE ADD COLUMN DEPARTMENT VARCHAR(50) NOT NULL;
ALTER TABLE OFFICE DROP COLUMN DEPARTMENT;

